### ISSUE TITLE
Flopcount mismatch and bad results on UCF101 compared to GluonCV implementation

### ISSUE THREAD

**Issue by huang-ziyuan** [facebookresearch/SlowFast#111]
I tried to train SlowFast 4x16, Res50 version on UCF101 and found this.
a) The flop count for this model is displayed as follows:
```
[INFO: misc.py:  100]: Params: 33,791,021
[INFO: misc.py:  101]: Mem: 261.55078125 MB
[WARNING: flop_count.py:  120]: Skipped operation aten::clone 664 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::add_ 111 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::mul_ 330 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::eq 110 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::batch_norm 110 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::relu_ 102 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::max_pool3d 4 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::cat 5 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::add 32 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::avg_pool3d 2 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::permute 1 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::dropout 1 time(s)
[WARNING: flop_count.py:  120]: Skipped operation aten::Int 1 time(s)
[INFO: misc.py:  103]: FLOPs: 27.63797632 GFLOPs
```
However, in the original paper, for the 4x16, R50 version, the flopcount should be 36.1 GFLOPs.

b) The top result I can get for training SlowFast 4x16, R50 on UCF101 from scratch is 73.49 for top1 accuracy and 88.82 for top5 accuracy, and that is trained for 512 epochs, while using GluonCV implementation, the same model trained with only 64 epochs could achieve as high as 92 for top1 accuracy.

Combined with the GFLOP count mismatch, is it reasonable to say there could be some error in the model?

**Comment by huang-ziyuan** [comment]
This is related to #100 and possibly related to #110.

**Comment by tonysy** [comment]
@huang-ziyuan  Hi, could you share the dataset implementation for UCF101 with this codebase? Thanks a lot.

**Comment by takatosp1** [comment]
Hi @huang-ziyuan, thanks a lot for playing with PySlowFast!
Regarding to 
a) In the [V1](https://arxiv.org/pdf/1812.03982v1.pdf) of SlowFast paper, we reports the FLOPs in the training setting, with the input size is 224x224, which is 27.6 in Table (e). In the [V3](https://arxiv.org/pdf/1812.03982.pdf) we report the FLOPs in the testing setting, with the input size is 256x256, which is 36.1 as you mentioned. 
```
Table 5. Ablations on the Fast pathway design on Kinetics-400. We show top-1 and top-5 classification accuracy (%), as well as computational complexity measured in GFLOPs  for a single clip input of spatial size 256^2. Inference-time computational cost is proportional to this, as a fixed number of 30 of views is used. Backbone: 4×16, R-50.
```
The 27.6 you saw is in training setting (you run with train_net.py). If you want to get the FLOP with testing setting, you could run it with test_net.py.

a) Regarding to the ucf 101 performance, we haven't release any recipe for it, so I am not sure what exactly setting you are using for now. I am also not sure what recipe do you use to get 92 on GluonCV, because I did not find it [in](https://gluon-cv.mxnet.io/model_zoo/action_recognition.html). 

I haven't search for the recipe, I just launched a simple job (with Kinetics pretrain) and got 92.97 with a 4x16 SlowOnly setting (only 4 frames as input), I expect higher number with more frames (8x8 or 32x2), and I also expect even higher number with SlowFast model.

We will release the UCF recipe soon in case if you need it.

Thanks again for playing with PySlowFast!

**Comment by takatosp1** [comment]
BTW, I'm performing a test on the SlowFast 4x16 model, and I will share you the update it has any wired behave.

**Comment by huang-ziyuan** [comment]
> BTW, I'm performing a test on the SlowFast 4x16 model, and I will share you the update it has any wired behave.

Thanks very much for your fast reply! The FLOP calculation is clear to me now.

For the UCF101, I used the same recipe as described in the paper for training Kinetics, and the same parameter settings as well. The only difference between your experiment several minutes ago and mine should be that yours is tested with Kinetics pretrain and mine was trained from scratch, and that I used 0.1 base lr without any tuning of the last layer. Just trained it straight for 64 epochs. 

I can share the training log later when I finish training using the latest version of the codebase, with parameter settings specified in the yaml file as well.

**Comment by tonysy** [comment]
@takatosp1  Thanks for you sharing, could you release the dataset implementation for UCF, I think the data preprocessing may have a big influence on the final accuracy. Thanks a lot.

**Comment by huang-ziyuan** [comment]
> @takatosp1 Thanks for you sharing, could you release the dataset implementation for UCF, I think the data preprocessing may have a big influence on the final accuracy. Thanks a lot.

Hi, I didn't change much in the Kinetics dataloader. Just used a script to generate csv files for train and val, so that the loader can read videos using the same script with the Kinetics dataloader. Other than that, the data loading process for UCF101 in my case is completely identical to the Kinetics loader.

**Comment by takatosp1** [comment]
@huang-ziyuan for ucf, you could use this yaml to get 94.5.

```
TRAIN:                                                                                      
  ENABLE: True                                                                              
  DATASET: kinetics                                                                         
  BATCH_SIZE: 64                                                                            
  EVAL_PERIOD: 10                                                                           
  CHECKPOINT_PERIOD: 1                                                                      
  AUTO_RESUME: True                                                                         
DATA:                                                                                       
  NUM_FRAMES: 8                                                                             
  SAMPLING_RATE: 8                                                                          
  TRAIN_JITTER_SCALES: [256, 320]                                                           
  TRAIN_CROP_SIZE: 224                                                                      
  TEST_CROP_SIZE: 256                                                                       
  INPUT_CHANNEL_NUM: [3]                                                                    
RESNET:                                                                                     
  ZERO_INIT_FINAL_BN: True                                                      
  WIDTH_PER_GROUP: 64                                                                       
  NUM_GROUPS: 1                                                                             
  DEPTH: 50                                                                                 
  TRANS_FUNC: bottleneck_transform                                                          
  STRIDE_1X1: False                                                                         
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]                                               
NONLOCAL:                                                                                   
  LOCATION: [[[]], [[]], [[]], [[]]]                                                        
  GROUP: [[1], [1], [1], [1]]                                                               
  INSTANTIATION: softmax                                                                    
BN:                                                                             
  USE_PRECISE_STATS: True                                                       
  NUM_BATCHES_PRECISE: 50                                                                   
  MOMENTUM: 0.1                                                                             
  WEIGHT_DECAY: 0.0                                                             
SOLVER:                                                                         
  BASE_LR: 0.01                                                                 
  LR_POLICY: cosine                                                             
  MAX_EPOCH: 196                                                                
  MOMENTUM: 0.9                                                                 
  WEIGHT_DECAY: 1e-4                                                            
  WARMUP_EPOCHS: 34                                                             
  WARMUP_START_LR: 0.01                                                         
  OPTIMIZING_METHOD: sgd                                                        
MODEL:                                                                          
  NUM_CLASSES: 101                                                              
  ARCH: i3d                                                                     
  LOSS_FUNC: cross_entropy                                                      
  DROPOUT_RATE: 0.5                                                             
TEST:                                                                           
  ENABLE: True                                                                  
  DATASET: kinetics                                                             
  BATCH_SIZE: 64                                                                
DATA_LOADER:                                                                    
  NUM_WORKERS: 8                                                                
  PIN_MEMORY: True                                                              
NUM_GPUS: 8                                                                     
NUM_SHARDS: 1
```

**Comment by takatosp1** [comment]
Hi @tonysy, thanks for playing with PySlowFast!
If you want to play with UCF101 now, you could follow what @huang-ziyuan shared, by just using a different csv file. 
We will also have some update to official support UCF101.

**Comment by huang-ziyuan** [comment]
@takatosp1 Thanks for sharing this. I'll try different recipes.
I still didn't understand why the result of GluonCV implementation (for SlowFast) is different from the result generated by this codebase using the same recipe. And you also haven't achieved 90+ using SlowFast architecture training from scratch, right? Since the file you just shared was based on i3d arch. 
Anyway.. probably there's some intrinsic difference in the training process of two different frameworks...

**Comment by takatosp1** [comment]
@huang-ziyuan could you please kindly enough share me the reference of the 92 number you referred?

**Comment by huang-ziyuan** [comment]
@takatosp1 I basically just ran the same script provided by GlueonCV on UCF101.
The script is as follows:
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python train_video_new.py \
    --dataset ucf101 \
    --data-dir /mnt/WXRC0021/users/yichenzhou/mxnet_shared/datasets/ucf101/rawframes \
    --train-list /mnt/WXRC0021/users/yichenzhou/mxnet_shared/datasets/ucf101/ucfTrainTestlist/ucf101_train_split_1_rawframes.txt \
    --val-list /mnt/WXRC0021/users/yichenzhou/mxnet_shared/datasets/ucf101/ucfTrainTestlist/ucf101_val_split_1_rawframes.txt \
    --dtype float32 \
    --mode hybrid \
    --prefetch-ratio 1.0 \
    --model slowfast_4x16_resnet50p_ucf101 \
    --slowfast \
    --slow-temporal-stride 16 \
    --fast-temporal-stride 2 \
    --num-classes 101 \
    --batch-size 8 \
    --num-gpus 8 \
    --num-data-workers 64 \
    --input-size 224 \
    --new-height 256 \
    --new-width 340 \
    --new-length 64 \
    --new-step 1 \
    --lr-mode cosine \
    --lr 0.1 \
    --momentum 0.9 \
    --wd 0.0001 \
    --num-epochs 64 \
    --warmup-epochs 16 \
    --warmup-lr 0.001 \
    --scale-ratios 1.0,0.8 \
    --save-frequency 16 \
    --log-interval 10 \
    --logging-file slowfast_4x16_resnet50p_ucf101.log \
    --save-dir ./logs/ 
```
and the result is 
top1  | top 5
92.13 | 98.15

**Comment by takatosp1** [comment]
Hi @huang-ziyuan,
I also check the training from scratch result on GluonCV from [here](https://github.com/dmlc/gluon-cv/tree/master/scripts/action-recognition), seems the performance is 60+. 

Could you please confirm when you referring the accuracy, you meant testing accuracy (not training accuracy)?

Thanks a lot!

**Comment by tonysy** [comment]
@huang-ziyuan Thanks for your sharing, one more question. Did you resize the video to the short edge size of 256 for the UCF dataset?

**Comment by takatosp1** [comment]
@tonysy you don't have to resize it.

**Comment by huang-ziyuan** [comment]
@takatosp1 Yes, the accuracy is testing accuracy. I uploaded one of the training logs [here](https://github.com/facebookresearch/SlowFast/files/4157455/log.log). 
Thanks for the effort. 60+ is close to my result of this codebase with original settings of Kinetics on UCF101. Probably something went wrong in my GlueonCV experiment. I will double-check and get back to you.

**Comment by huang-ziyuan** [comment]
@tonysy Like @takatosp1 mentioned you don't have to resize it. But in my experiments, I performed the resize anyway, to a random number between 256 to 320 as mentioned in the SlowFast paper.

**Comment by takatosp1** [comment]
@huang-ziyuan thanks, looking forward to hearing the update from you. 
I am very excited to see what is the magic :P

**Comment by takatosp1** [comment]
Any updates @huang-ziyuan? (no rush but I am extremely curious how could you able to train from scratch on UCF101 to get 92 with the simplest SF model).

**Comment by huang-ziyuan** [comment]
@tonysy Hey, thanks, it's nice of you to pay so much attention to this. I haven't figured out the mystery of the 90+ performance yet. But I did perform a test on the yaml configuration that you gave me yesterday. Unfortunately, the result wasn't satisfactory. I attach the 
[training_log.log](https://github.com/facebookresearch/SlowFast/files/4163207/training_log.log) and the [test_log.log](https://github.com/facebookresearch/SlowFast/files/4163208/test_log.log), and the content for YAML file down below as well. The test result with 30 views was only 60+ for top1. 

This is weird because I haven't actually succeeded in getting the performance over 75 for top1 on this codebase. 

Meanwhile, I will continue looking for the answer to the 90+ mystery.

Here's the yaml file that I used, which should be identical to yours except for the adaptation made to be compatible to the latest version of this codebase.
```
TRAIN:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 128
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 50
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 101
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: ucf101
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
```
