### ISSUE TITLE
Cannot reproduce the result on AVA

### ISSUE THREAD

**Issue by taosean** [facebookresearch/SlowFast#141]
Hi, thank you for your great code base.

Now I'm trying to reproduce the result on AVA claimed in paper and tech report. However, I cannot reproduce the result.
I chose [configs/AVA/c2/SLOWFAST_32x2_R101_50_50.yaml](https://github.com/facebookresearch/SlowFast/blob/master/configs/AVA/c2/SLOWFAST_32x2_R101_50_50.yaml) configuration file for training.
The modifications I did to this config file are: (**Here, the commented are original settings**.)
```yaml
TRAIN:
  ENABLE: True #False
  DATASET: ava
  BATCH_SIZE: 80 #16
  EVAL_PERIOD: 2 # 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: path to pretrain model downloaded from the third entry in this table(https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md#ava)
  CHECKPOINT_TYPE: caffe2 # pytorch
DETECTION:
  ENABLE: True
  ALIGNED: True #False
#SOLVER:
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-7
#  OPTIMIZING_METHOD: sgd
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 20, 30]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 40
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
```

As you can see, I modified the learning policy from `cosine` to `steps_with_relative_lrs`, which is stated in paper, with reference to the settings in https://github.com/facebookresearch/SlowFast/blob/a8a47ced376a681e76d8b904e7be76d67fe999b3/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml#L52-L62
However, the result is not good.

Below is the picture of training loss and mAP on val set, 
![批注 2020-03-10 134205](https://user-images.githubusercontent.com/17960909/76285609-21a45880-62db-11ea-9557-7aa169a48ffe.jpg)

From the picture, we can find that the mAP on Val set saturates around `26 .0` quickly and cannot reach the value (**`29.0`**) stated in paper.

How do you think about this, is this because of the `STEPS` parameter I set that cause overfitting?

Thank you!

**Comment by takatosp1** [comment]
Hi 
Thanks for playing with PySlowFast!
I noticed you've change the batch size, as well as the ALIGN, they all affect the performance significantly. Also I am curious that how could you run a SlowFast R101 model with batch size of 80? Could you share me what are the number of GPUs you use?

btw, note that, for the scripts under `/c2/`, they are script designed to use for inference.

**Comment by taosean** [comment]
Hi @takatosp1 , thank you for your reply.

I'm training my model on a machine with 8 Quadro RTX 6000 GPUs (24G memory).

---
> I noticed you've change the batch size, as well as the ALIGN, they all affect the performance significantly.

I noticed that in 
https://github.com/facebookresearch/SlowFast/blob/a8a47ced376a681e76d8b904e7be76d67fe999b3/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml#L1-L9

that batchsize is set to `64`, since my batchsize is `80`, now I'm doing another training with 
```yaml
DETECTION:
  ENABLE: True
  ALIGNED: True
SOLVER:
  BASE_LR: 0.125 #0.1
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 8, 12]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 16
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
```

with the
```yaml
  BASE_LR: 0.125 #0.1
  STEPS: [0, 8, 12]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 16
```
calculated according to 
https://github.com/facebookresearch/SlowFast/blob/a8a47ced376a681e76d8b904e7be76d67fe999b3/configs/AVA/SLOWFAST_32x2_R50_SHORT.yaml#L52-L62
are these settings correct?

Besides, how is `ALIGN` going to affect the performance? Are the models claimed in paper trained with `ALIGN` set to `True` or `False`?

---

>btw, note that, for the scripts under /c2/, they are script designed to use for inference.

Thank you for reminding. 
However, if so, there are no scripts for training with R101 model, right? It it OK if I modify the inference script for training?

Best regards!
