### ISSUE TITLE
Preparation of AVA-Dataset Format for Training on Custom Dataset

### ISSUE THREAD

**Issue by NaeemKhan333** [facebookresearch/SlowFast#149]
Thanks for nice work . I have seen the "demo.gif" which is the output of the model which is trained on the "AVA-Dataset" .Now I want to convert my custom dataset into "AVA-Dataset Format" and want to train a model using your given code . Can you guide me what are pre-processing steps I need to do to convert my own custom dataset into the AVA Dataset Format. Can you give me brief idea or any tools which help me to achieve the "AVA-Dataset Format" . Thanks

I have data set now as follow
```
Dataset/
├── Class-A
│         └── insp.mp4
├── Class-B
│          └── kep.mp4
└── Class-C
             └── tak.mp4 
```

**Comment by ldtuanAPCS** [comment]
Hi all, I am also want to train on my own dataset with SlowFast. The structure of my dataset is the same as @NaeemKhan333 but the frames are already extracted. Hope to hear from you soon.

**Comment by rashidch** [comment]
Hey,
I am also looking for instructions to train on a custom dataset. My custom dataset has only videos in directory. Kindly provide the documentation to train custom dataset. 

Thanks!

**Comment by AlexanderMelde** [comment]
I would also appreciate further documentation, i can't find a good guide yet on how to train and test with own videos using a [pretrained model](https://github.com/facebookresearch/SlowFast/blob/master/MODEL_ZOO.md).

**Comment by harshsp31** [comment]
Hi @NaeemKhan333,  @takatosp1 
Any updates on this issue? I am also stuck at dataset preparation. Any progress will help me a lot! Thanks

**Comment by EricWiener** [comment]
Has anyone had any progress with this?

**Comment by AlexanderMelde** [comment]
Yes! Let's say your dataset is named `MyData`, you should structure your files and folders like this:

```
SlowFast/
├── configs/
│       └── MyData/
│               └── I3D_8x8_R50.yaml
├── data/
│       └── MyData/
│               ├── ClassA/
│               │      └── ins.mp4
│               ├── ClassB/
│               │      └── kep.mp4
│               ├── ClassC/
│               |      └── tak.mp4
│               ├── train.csv
│               ├── test.csv
│               ├── val.csv
│               └── classids.json
├── slowfast/
│       └── datasets/
│               ├── __init__.py
│               ├── mydata.py
│               └── ...
└── ...
```

As you can see, you will need to create a config file (`.yaml`), three files for the dataset split (`.csv`), a file for referencing classes (`.json`) and a file for dataset parsing (`mydata.py`). 

To create the python file `mydata.py`, duplicate [`kinetics.py`](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/datasets/kinetics.py) which is located in the same folder, rename it to `mydata.py` and replace all occurences of `Kinetics` by `Mydata` (search and replace, case-sensitive)

Once created, you will also need to import the newly created python file to the project by adding the line `from .mydata import Mydata` to the `__init__.py` file in the same folder.


The `classids.json` file contains a mapping of class names and ids. It will look like the following:

```
{"ClassA": 0, "ClassB": 1, "ClassC": 2}
```

The `.csv` files define which of the videos will be used for training, validation and inference testing, and which classes they reference. 

They should look like the following:

```
/SlowFast/data/MyData/ClassA/ins.mp4 0
/SlowFast/data/MyData/ClassC/tak.mp4 2
```

For larger datasets, it will propably be the easiest to create files like this using an automated script that parses `classids.json` and the folder structure.

Note that all three files should not share any identical lines (use the same video) and pay attention to your actual paths (absolute or relative paths can be used).


Last but not least, you will need to create a configuration file to train or test the network. 
You can copy an existing one from the `SlowFast/configs/Kinetics` folder, e.g. [`I3D_8x8_R50.yaml`](https://github.com/facebookresearch/SlowFast/blob/master/configs/Kinetics/I3D_8x8_R50.yaml).

In the copied file, replace all occurences of `kinetics` by `mydata` (case-sensitive).

You can run SlowFast with the new config that references your own dataset by running

```
python /SlowFast/tools/run_net.py --cfg /SlowFast/configs/MyData/I3D_8x8_R50.yaml
```

Note that you might need to adjust pathes to your actual working directory.

I hope this guide will help you guys using SlowFast with your own datasets :)

**Comment by EricWiener** [comment]
@AlexanderMelde thank you so much! This is beyond helpful

**Comment by wwdok** [comment]
Hi, anyone here, could you please share me the file of `AVA class names json file`, because now it is broken ! many thanks！
![image](https://user-images.githubusercontent.com/43233772/98655510-86d4b000-237a-11eb-89ea-40cedf93c67e.png)

**Comment by wwdok** [comment]
@AlexanderMelde Hi, i basically followed your instructions, but encounter abnormal logging,  you can look at this [issue](https://github.com/facebookresearch/SlowFast/issues/327), could you please give me some tips ?

then i want to run the demo with my trained model, do i just need to configure `CHECKPOINT_FILE_PATH` with the path of trained model in the SLOWFAST_8x8_R50.yaml ？ but i find  its original format is .pkl, but the foramt of trained model is .pyth, so can i use .pyth for the `CHECKPOINT_FILE_PATH` ?

**Comment by AlexanderMelde** [comment]
> do i just need to configure `CHECKPOINT_FILE_PATH` with the path of trained model in the SLOWFAST_8x8_R50.yaml?

Yes, but instead you could also set [`TRAIN.AUTO_RESUME = True`](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/config/defaults.py#L61).

> but i find its original format is .pkl, but the format of trained model is .pyth, so can i use .pyth for the `CHECKPOINT_FILE_PATH` ?

Yes you can use both formats, just set [`TRAIN.CHECKPOINT_TYPE = "pytorch"`](https://github.com/facebookresearch/SlowFast/blob/master/slowfast/config/defaults.py#L67).

**Comment by wwdok** [comment]
@AlexanderMelde 
**My case**: 
* only one action class : "fall_down"
* dataset comes from [HMDB51 "fall floor" subset](https://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/#Downloads), one of the video is like [this](https://streamja.com/rLJ6e).
* BATCH_SIZE: 2

I use 4 print function
```
                print("==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~")
                print("preds is {}".format(preds.tolist()))
                print("labels is {}".format(labels.tolist()))
                num_topks_correct = metrics.topks_correct(preds, labels, (1))
                print("preds.size(0) is {}".format(preds.size(0)))
                print("num_topks_correct is {}".format(num_topks_correct))
                top1_err= [(1.0 - x / preds.size(0)) * 100.0 for x in num_topks_correct][0]
```
in `def train_epoch()` to check preds and labels, part of its output is :
```
[11/17 15:35:50][INFO] train_net.py: 419: Start epoch: 2
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.03573627024888992], [-0.32597339153289795]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.30879950523376465], [-0.02247714065015316]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[0.05403393507003784], [-0.18906450271606445]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.18617770075798035], [-0.16703137755393982]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[0.10825307667255402], [-0.292312890291214]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.0778438001871109], [-0.07582096755504608]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.30321329832077026], [-0.11427342891693115]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.09245844930410385], [-0.25378167629241943]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.2726392149925232], [0.0589011125266552]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
==============!!!!!!!!!!!!!!!!!!!!!!~~~~~~~~~~~~~~~~~
preds is [[-0.07824113965034485], [-0.22474029660224915]]
labels is [0, 0]
preds.size(0) is 2
num_topks_correct is [tensor(2., device='cuda:0')]
[11/17 15:35:59][INFO] logging.py:  96: json_stats: {"_type": "train_iter", "dt": 0.75530, "dt_data": 0.00388, "dt_net": 0.75142, "epoch": "2/10", "eta": "0:01:20", "gpu_mem": "2.78G", "iter": "10/13", "loss": 0.00000, "lr": 0.00972, "top1_err": 0.00000}
```
the predition is negtive, is it normal ? i didn't enable DETECTION in yaml.

my yaml is :
```
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 2  
  EVAL_PERIOD: 10  
  CHECKPOINT_FILE_PATH: "./demo/Kinetics/SLOWFAST_8x8_R50.pkl"  
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: "/media/weidawang/DATA/dataset/HMDB51/hmdb51_org/fall_floor"
  PATH_LABEL_SEPARATOR: ","
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0125  
  LR_POLICY: cosine
  MAX_EPOCH: 10  
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 1 
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 2  
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1  
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
```
