### ISSUE TITLE
Strange GPU consumption in slowfast+multigrid 

### ISSUE THREAD

**Issue by SuX97** [facebookresearch/SlowFast#277]
Hi,

I found the memory consumption when using multigrid is not consist with vanilla slowfast.

Here are two snippets from my log:

w/o multigrid (SLOWFAST_8x8_R50.yaml used):
```
 'TRAIN': {'AUTO_RESUME': False,
           'BATCH_SIZE': 64,
           'CHECKPOINT_FILE_PATH': '',
           'CHECKPOINT_INFLATE': False,
           'CHECKPOINT_PERIOD': 1,
           'CHECKPOINT_TYPE': 'pytorch',
           'DATASET': 'kinetics',
           'ENABLE': True,
           'EVAL_PERIOD': 10}}
          'NUM_FRAMES': 32,
          'PATH_LABEL_SEPARATOR': ' ',
          'PATH_PREFIX': '',
...
          'RANDOM_FLIP': True,
          'REVERSE_INPUT_CHANNEL': False,
          'SAMPLING_RATE': 2,
          'STD': [0.225, 0.225, 0.225],
          'TARGET_FPS': 30,
          'TEST_CROP_SIZE': 256,
          'TRAIN_CROP_SIZE': 224,
          'TRAIN_JITTER_SCALES': [256, 320]},

[07/15 23:45:33][INFO] slowfast.utils.logging:   96: json_stats: {"_type": "train_iter", "epoch": "1/196", "eta": "8 days, 2:10:12", "gpu_mem": "10.06 GB", "iter": "10/3756", "loss": 6.034320, "lr": 0.010006, "time_diff": 0.949530, "top1_err": 98.437500, "top5_err": 96.875000}
```
Note the gpu_mem is 10.06GB.

w/ multigrid (SLOWFAST_8x8_R50_stepwise_multigrid.yaml used):
```
[09/02 18:12:03][INFO] slowfast.utils.logging:   96: json_stats: {"_type": "train_iter", "epoch": "1/358", "eta": "1 day, 20:30:58", "gpu_mem": "24.93 GB", "iter": "10/352", "loss": 6.116960, "lr": 0.010594, "time_diff": 1.271830, "top1_err": 99.414062, "top5_err": 97.949219}
```
Note the gpu_mem is 24.93GB.

The input tensor in multigrid training should have the same number of elements as the vanilla one, it confused me why it takes more GPU memory.

Thank you!

**Comment by chaoyuaw** [comment]
Hi @SuX97 , Thanks for your question. 

Did you set cudnn.benchmark=True in your experiments? I wonder if different cudnn conv algorithm selections cause the issue. 

I haven't seen this issue before, but I wonder if printing the shapes of input tensors to see which specific "batch shape" causes the large memory consumption would be a helpful first step to figure this out.

**Comment by SuX97** [comment]
Hi,
I cannot find any code related to specific cudnn.benchmark, thus regardless to whether cudnn opened or not, I assume the setting for two experiments are the same.
I add a breakpoint at the begining of the forward in [`stem_helper.py`](https://github.com/facebookresearch/SlowFast/blob/0cc82440fee6e51a5807853b583be238bf26a253/slowfast/models/stem_helper.py#L174), and print the input tensor's shape by `x.size()`, the batch dimension seems also wired.

![image](https://user-images.githubusercontent.com/25632694/92352789-74878d00-f111-11ea-8649-3ded2224df7b.png)

I wonder why the batch dimension is '1'. The time and spatial dimension seems to be ok, which is 8 * long_cycle_time_factor[0](1/4) and 224 * short_cycle_factor[0](sqrt(2)). But the batch should be 8 times, which is 8 * 8 = 64.

Could you please verify this problem by your own machine? Actually in my own implementation, I also find the gpu memory to be significant larger though the shape is right.

Below is my config printed by logger, hope that may help.
```yaml
MULTIGRID:
  SHORT_CYCLE: True
  LONG_CYCLE: True
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 94, 154, 196]
  MAX_EPOCH: 239
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./debug_multi_grid_0902

```
