### ISSUE TITLE
ValueError: Type mismatch (<class 'list'> vs. <class 'bool'>) with values ([] vs. True) for config key: TENSORBOARD.MODEL_VIS.LAYER_LIST

### ISSUE THREAD

**Issue by jpainam** [facebookresearch/SlowFast#495]
Hi. I'm trying to fill in the layer list using a configuration file
```
TENSORBOARD:
  ENABLE: True
  LOG_DIR:
  CLASS_NAMES_PATH: /xxx/home/xxx/data/class_names.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /xxx/home/xxx/data/class_names.txt
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    LAYER_LIST: True
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ["s5/pathway1_res2", "s5/pathway0_res2"]
```
But I get this error `ValueError: Type mismatch (<class 'list'> vs. <class 'bool'>) with values ([] vs. True) for config key: TENSORBOARD.MODEL_VIS.LAYER_LIST`
