### ISSUE TITLE
Getting RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by DreamyBit** [facebookresearch/SlowFast#628]
Hi

I'm currently trying to train a MViTv2 model using the RWF-2000 dataset (2k short videos in .avi, 2 classes), so far managed to set the data as per [this](https://github.com/facebookresearch/SlowFast/issues/480) guide and tried to start the training using a slightly modified version of [/configs/Kinetics/MVITv2_S_16x4.yaml](https://github.com/facebookresearch/SlowFast/blob/main/configs/Kinetics/MVITv2_S_16x4.yaml).

But as soon as the epoch 1 starts I get the following error:
```
[11/29 11:02:00][INFO] train_net.py:  631: Start epoch: 1
Traceback (most recent call last):
  File "tools/run_net.py", line 52, in <module>
    main()
  File "tools/run_net.py", line 27, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=train)
  File "/workspace/slowfast/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/workspace/slowfast/tools/train_net.py", line 681, in train
    train_epoch(
  File "/workspace/slowfast/tools/train_net.py", line 230, in train_epoch
    num_topks_correct = metrics.topks_correct(preds, labels, (1, 5))
  File "/workspace/slowfast/slowfast/utils/metrics.py", line 29, in topks_correct
    _top_max_k_vals, top_max_k_inds = torch.topk(
RuntimeError: selected index k out of range
```
full output here [console_output.txt](https://github.com/facebookresearch/SlowFast/files/10114009/console_output.txt)

Tried googling a solution but came back empty handed, my only guess is that the output layer of my model doesn't match my 2 classes but alas I don't know how to change the output size in the config either

Any help is appreciated. I'm using this config:

```
TRAIN:
    ENABLE: True
    DATASET: rwf2000
    BATCH_SIZE: 4
    EVAL_PERIOD: 10
    CHECKPOINT_PERIOD: 10
    AUTO_RESUME: True
DATA:
    USE_OFFSET_SAMPLING: True
    DECODING_BACKEND: pyav #pytorch default, https://github.com/facebookresearch/SlowFast/issues/181
    NUM_FRAMES: 8
    SAMPLING_RATE: 4
    TRAIN_JITTER_SCALES: [256, 320]
    TRAIN_CROP_SIZE: 224
    TEST_CROP_SIZE: 224
    INPUT_CHANNEL_NUM: [3]
    PATH_TO_DATA_DIR: data/Rwf2000
    TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
    TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
MVIT:
    ZERO_DECAY_POS_CLS: False
    USE_ABS_POS: False
    REL_POS_SPATIAL: True
    REL_POS_TEMPORAL: True
    DEPTH: 16
    NUM_HEADS: 1
    EMBED_DIM: 32 #96 default
    PATCH_KERNEL: (3, 7, 7)
    PATCH_STRIDE: (2, 4, 4)
    PATCH_PADDING: (1, 3, 3)
    MLP_RATIO: 4.0
    QKV_BIAS: True
    DROPPATH_RATE: 0.2
    NORM: "layernorm"
    MODE: "conv"
    CLS_EMBED_ON: True
    DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
    HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
    POOL_KVQ_KERNEL: [3, 3, 3]
    POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
    POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
    DROPOUT_RATE: 0.0
    DIM_MUL_IN_ATT: True
    RESIDUAL_POOLING: True
AUG:
    NUM_SAMPLE: 2
    ENABLE: True
    COLOR_JITTER: 0.4
    AA_TYPE: rand-m7-n4-mstd0.5-inc1
    INTERPOLATION: bicubic
    RE_PROB: 0.25
    RE_MODE: pixel
    RE_COUNT: 1
    RE_SPLIT: False
MIXUP:
    ENABLE: True
    ALPHA: 0.8
    CUTMIX_ALPHA: 1.0
    PROB: 1.0
    SWITCH_PROB: 0.5
    LABEL_SMOOTH_VALUE: 0.1
SOLVER:
    ZERO_WD_1D_PARAM: True
    BASE_LR_SCALE_NUM_SHARDS: True
    CLIP_GRAD_L2NORM: 1.0
    BASE_LR: 0.0001
    COSINE_AFTER_WARMUP: True
    COSINE_END_LR: 1e-6
    WARMUP_START_LR: 1e-6
    WARMUP_EPOCHS: 30.0
    LR_POLICY: cosine
    MAX_EPOCH: 200
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.05
    OPTIMIZING_METHOD: adamw
    COSINE_AFTER_WARMUP: True
MODEL:
    NUM_CLASSES: 2
    ARCH: mvit
    MODEL_NAME: MViT
    LOSS_FUNC: soft_cross_entropy
    DROPOUT_RATE: 0.5
TEST:
    ENABLE: True
    DATASET: kinetics
    BATCH_SIZE: 64
    NUM_SPATIAL_CROPS: 1
    NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
    NUM_WORKERS: 1
    PIN_MEMORY: True
NUM_GPUS: 1 # 8 default
NUM_SHARDS: 0 # 1 default
RNG_SEED: 0
OUTPUT_DIR: .

```
