### ISSUE TITLE
Where is the model saved after training? and how do you test it?

### ISSUE THREAD

**Issue by DreamyBit** [facebookresearch/SlowFast#632]
Hi there

I've been training a model to detect violence in videos using **MViTv2** on the **RWF-2000** dataset. After the training is complete it runs a test as is specified in the config but since there are only two classes (Violence or Not) the top5 metric doesn't really make sense.

So, there's a way to test the model using all the videos on the _test.csv_ using another metric?

This is the config I've been using
```yaml
TRAIN:
  ENABLE: True
  DATASET: rwf2000
  BATCH_SIZE: 1
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: pyav #pytorch default, https://github.com/facebookresearch/SlowFast/issues/181
  NUM_FRAMES: 8
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data/Rwf2000
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96 #96 default
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0001
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 30.0
  LR_POLICY: cosine
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 2
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: rwf2000
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 1 # 8 default
NUM_SHARDS: 0 # 1 default
RNG_SEED: 0
OUTPUT_DIR: ./output

```

And this is the last section of what I assume is the test output >> not too sure on that tbh 

```sh
[12/20 01:11:50][INFO] misc.py:  191: Activations: 105.338351 M
[12/20 01:11:50][INFO] misc.py:  196: nvidia-smi
[12/20 01:11:50][INFO] checkpoint.py:  222: Loading network weights from ./output/checkpoints/checkpoint_epoch_00020.pyth.
[12/20 01:11:51][INFO] rwf2000.py:   84: Constructing Rwf2000 test...
[12/20 01:11:51][INFO] rwf2000.py:  149: Constructing Rwf2000 dataloader (size: 1000 skip_rows 0) from data/Rwf2000/test.csv 
[12/20 01:11:51][INFO] test_net.py:  219: Testing model for 16 iterations
[12/20 01:12:10][INFO] logging.py:   99: json_stats: {"cur_iter": "1", "eta": "0:05:12", "split": "test_iter", "time_diff": 19.54811}
[12/20 01:12:18][INFO] logging.py:   99: json_stats: {"cur_iter": "2", "eta": "0:02:03", "split": "test_iter", "time_diff": 8.21730}
[12/20 01:12:30][INFO] logging.py:   99: json_stats: {"cur_iter": "3", "eta": "0:02:42", "split": "test_iter", "time_diff": 11.61174}
[12/20 01:12:49][INFO] logging.py:   99: json_stats: {"cur_iter": "4", "eta": "0:04:03", "split": "test_iter", "time_diff": 18.73380}
[12/20 01:13:03][INFO] logging.py:   99: json_stats: {"cur_iter": "5", "eta": "0:02:47", "split": "test_iter", "time_diff": 13.92943}
[12/20 01:13:19][INFO] logging.py:   99: json_stats: {"cur_iter": "6", "eta": "0:02:57", "split": "test_iter", "time_diff": 16.17192}
[12/20 01:13:34][INFO] logging.py:   99: json_stats: {"cur_iter": "7", "eta": "0:02:29", "split": "test_iter", "time_diff": 14.90137}
[12/20 01:13:52][INFO] logging.py:   99: json_stats: {"cur_iter": "8", "eta": "0:02:41", "split": "test_iter", "time_diff": 17.95047}
[12/20 01:14:04][INFO] logging.py:   99: json_stats: {"cur_iter": "9", "eta": "0:01:38", "split": "test_iter", "time_diff": 12.28316}
[12/20 01:14:12][INFO] logging.py:   99: json_stats: {"cur_iter": "10", "eta": "0:00:59", "split": "test_iter", "time_diff": 8.49900}
[12/20 01:14:25][INFO] logging.py:   99: json_stats: {"cur_iter": "11", "eta": "0:01:17", "split": "test_iter", "time_diff": 12.91661}
[12/20 01:14:37][INFO] logging.py:   99: json_stats: {"cur_iter": "12", "eta": "0:00:58", "split": "test_iter", "time_diff": 11.69021}
[12/20 01:14:45][INFO] logging.py:   99: json_stats: {"cur_iter": "13", "eta": "0:00:32", "split": "test_iter", "time_diff": 8.24497}
[12/20 01:14:58][INFO] logging.py:   99: json_stats: {"cur_iter": "14", "eta": "0:00:37", "split": "test_iter", "time_diff": 12.63337}
[12/20 01:15:05][INFO] logging.py:   99: json_stats: {"cur_iter": "15", "eta": "0:00:13", "split": "test_iter", "time_diff": 6.91627}
[12/20 01:15:11][INFO] logging.py:   99: json_stats: {"cur_iter": "16", "eta": "0:00:06", "split": "test_iter", "time_diff": 6.06957}
[12/20 01:15:11][INFO] logging.py:   99: json_stats: {"split": "test_final", "top1_acc": "100.00", "top5_acc": "100.00"}
[12/20 01:15:11][INFO] test_net.py:  260: Finalized testing with 5 temporal clips and 1 spatial crops
[12/20 01:15:11][INFO] test_net.py:  282: _p34.22_f28.62_5a100.00 Top5 Acc: 100.00 MEM: 6.50 f: 28.6218
[12/20 01:15:11][INFO] test_net.py:  283: _p34.22_f28.62_5a100.00
```
