### ISSUE TITLE
Help with Configuration File and Issue with Input Pathway Dimensions

### ISSUE THREAD

**Issue by GMBarra** [facebookresearch/SlowFast#650]
Hello everyone,

I have been trying to utilize the SlowFast library for a project, but have been encountering some difficulties with understanding the configuration file and resolving an input pathway dimensions error.

My project involves using a series of .avi videos from surveillance cameras for classification. The challenge here is that the videos come in different sizes. An additional piece of information is that each video I am working with is a clip of 150 frames.

Following [this guide](https://github.com/facebookresearch/SlowFast/issues/149#issuecomment-723265461), I adjusted the configuration settings and the data accordingly. However, I am met with the following error:

AssertionError: Input pathway dimensions are not consistent. 1 2 2 2 2

This is my current configuration:

[Include your configuration here]

My main questions are:

```
TRAIN:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 2  
  EVAL_PERIOD: 10  
  #CHECKPOINT_FILE_PATH: "./demo/Kinetics/SLOWFAST_8x8_R50.pkl"  
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: "./slowfast/data/MyData"
  PATH_LABEL_SEPARATOR: ","
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0125  
  LR_POLICY: cosine
  MAX_EPOCH: 10  
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 1 
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: mydata
  BATCH_SIZE: 2  
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1  
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
```

Is there any resource available that explains the configuration variables in more detail? The current documentation does not seem to cover everything.
How can I adjust my configuration or pre-processing to handle different video sizes, and resolve the "Input pathway dimensions are not consistent" error?
With each video being a clip of 150 frames, is there a specific setting or adjustment I need to consider in the configuration?

Any help or advice would be greatly appreciated.
