### ISSUE TITLE
whats the meaning of yaml file?

### ISSUE THREAD

**Issue by Leozyc-waseda** [facebookresearch/SlowFast#678]
If i want to change the temporal stride, frame ratio which meationed in the paper, how should i do it?
```
TRAIN:
  ENABLE: True
  DATASET: Mydata
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
```
