### ISSUE TITLE
OSError: Video /home/Project/input/in.mp4 cannot be opened

### ISSUE THREAD

**Issue by liveforeverneverdie** [facebookresearch/SlowFast#681]
Traceback (most recent call last):
  File "/root/Project/slowfast/tools/run_net.py", line 52, in <module>
    main()
  File "/root/Project/slowfast/tools/run_net.py", line 48, in main
    demo(cfg)
  File "/root/Project/slowfast/tools/demo_net.py", line 112, in demo
    frame_provider = VideoManager(cfg)
  File "/root/Project/slowfast/slowfast/visualization/demo_loader.py", line 49, in __init__
    raise IOError("Video {} cannot be opened".format(self.source))
OSError: Video /home/Project/input/in.mp4 cannot be opened

SLOWFAST_32x2_R101_50_50.yaml:

```
DEMO:
  ENABLE: True
  LABEL_FILE_PATH: "/home/Project/slowfast/demo/AVA/AVA.json" # Add local label file path here.
  INPUT_VIDEO: "/home/Project/input/in.mp4"
  OUTPUT_FILE: "/home/Project/output/out.mp4"
#  WEBCAM: -1
  DETECTRON2_CFG: "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
  DETECTRON2_WEIGHTS: detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl
```

I think path of mp4 should be correct, but it just can't be opened. And I have "chmod" mp4.
Hopefully someone helps.
