### ISSUE TITLE
Why did I test the slowfast model officially provided and get a very low or wrong mAp (0.039) on the ava dataset? Do you have any ideas or suggestions?

### ISSUE THREAD

**Issue by 1298109106** [facebookresearch/SlowFast#710]
When I was testing the official model (downloaded from Model ZOO), I got the wrong mAp, do you have any ideas or suggestions?
![image](https://github.com/facebookresearch/SlowFast/assets/52307287/1753b480-2d24-42c5-b64a-5b7758994be2)
The yaml file I use is as follows :(https://github.com/facebookresearch/SlowFast/blob/main/configs/AVA/c2/SLOWFAST_32x2_R101_50_50.yaml):
```
TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to pretrain model
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  PATH_TO_DATA_DIR: '/media/dsd/0c13c20e-65ea-4dbd-bd5a-146423aba7af/cpz/ava'
DETECTION:
  ENABLE: True
  ALIGNED: False
AVA:
  FRAME_DIR: '/media/dsd/0c13c20e-65ea-4dbd-bd5a-146423aba7af/cpz/ava/frames'
  FRAME_LIST_DIR: '/media/dsd/0c13c20e-65ea-4dbd-bd5a-146423aba7af/cpz/ava/frame_lists'
  ANNOTATION_DIR: '/media/dsd/0c13c20e-65ea-4dbd-bd5a-146423aba7af/cpz/ava/annotations'
  BGR: False
  DETECTION_SCORE_THRESH: 0.8
  TEST_PREDICT_BOX_LISTS: ["person_box_67091280_iou90/ava_detection_val_boxes_and_labels.csv"]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 2
  CHECKPOINT_FILE_PATH: '/media/dsd/0c13c20e-65ea-4dbd-bd5a-146423aba7af/cpz/SlowFast-main/configs/AVA/c2/SLOWFAST_32x2_R101_50_50T.pkl'
  CHECKPOINT_TYPE: caffe2
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
```
Here are my result:
![image](https://github.com/facebookresearch/SlowFast/assets/52307287/d92b493b-c8f2-4b69-9ade-9fe327cfdb5b)
